### ISSUE TITLE
Not C++17 

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/FishStore#16]
had no time to delve deeper, but (for example) common_utils.h is not C++17 .. more of a C++98?

Is that intentional? question of implementation philosophy?

Please advise ...

**Comment by Skyprophet** [comment]
There are quite a bit of places in FishStore uses C++14 feature (like relaxed `constexpr`). C++17 is more of a left over which was used by one dependency in the internal version. Also, simdjson which is the dependent parser in the open source version requires C++17.
On 12/6/2019 02:54:26, dbj <notifications@github.com> wrote:
had no time to delve deeper, but (for example) common_utils.h is not C++17 .. more of a C++98?
Is that intentional? question of implementation philosophy?
Please advise ...

**Comment by dongx-psu** [comment]
Just tried C++14, and it doesn't work. C++17 is required. If it is not, `simdjson` would fail in compilation.

**Comment by DBJDBJ** [comment]
Ah ok, I see ... using C++17 goodies like: `std::string_view`, `std::optional`, `std::array` etc ... will make code smaller and perhaps more resilient .. I think.

Thanks
